name: Run Python script and push changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_python_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run Script
      env:
          THRD_PARS: '128'
          PARS_DP: '2'
          USE_INV_TC: 'n'
      run: |
        python tg-parser.py

    - name: Update files
      run: |
          echo "Configs" > "configtg.txt"
          echo "Channels" > "telegramchannelsjson"
          echo "Invalids" > "invalidtelegramchannels.json"
          
      
    - name: Commit and push
      run:
        git config -f user.name "GitHub Action"
        git config -f user.email "action@github.com"
        git commit -m "Update configs"
        git push https://${{ secrets.PAT }}@github.com/Surfboardv2ray/TGParse.git
